[project]
name = 'sunny_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.audit_log]
path = 'contracts/audit_log.clar'
clarity_version = 2
epoch = 2.5

[contracts.deposit_bonus_wallet]
path = 'contracts/deposit_bonus_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_deletion]
path = 'contracts/file_deletion.clar'
clarity_version = 2
epoch = 2.5

[contracts.split_withdrawal_wallet]
path = 'contracts/split_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_reset_delay]
path = 'contracts/storage_with_reset_delay.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
